import Link from 'next/link';
import { ArrowRight, ArrowLeft, Heart, Building2, Database, CheckCircle2 } from 'lucide-react';

const workflows = [
  { icon: Heart, title: 'Donor → LIFE-LINK', color: 'red', items: ['Donor creates a profile with blood group, location, and availability.', 'Donor details are verified.', 'Compatible nearby donors can be identified for emergencies.', 'Donors receive alerts and can respond to requests.'] },
  { icon: Building2, title: 'Hospital → LIFE-LINK', color: 'blue', items: ['Hospital raises an emergency blood request.', 'Required blood group, units, urgency, and request details are entered.', 'LIFE-LINK checks connected blood resources.', 'Hospitals can track request and fulfillment status.'] },
  { icon: Database, title: 'Blood Bank → LIFE-LINK', color: 'amber', items: ['Blood banks maintain current inventory.', 'Available groups, units, expiry/status, and location are recorded.', 'Nearby inventory can be checked for hospital requests.', 'Blood banks coordinate transfers and dispatch.'] },
];

export default function AboutPage() {
  return <div className="lifelink-page min-h-screen">
    <header className="public-header"><div className="lifelink-container h-16 flex items-center justify-between"><Link href="/" className="brand-mark"><span className="brand-mark-icon">+</span><span className="brand-mark-word">LIFE LINK</span></Link><nav className="hidden sm:flex gap-7"><Link href="/about" className="public-nav-link active">About</Link><Link href="/faq" className="public-nav-link">FAQ</Link><Link href="/contact" className="public-nav-link">Contact</Link></nav><Link href="/choose-role" className="h-9 px-4 rounded-lg bg-blue-600 text-white text-xs font-semibold flex items-center">Get started</Link></div></header>
    <main className="lifelink-container py-12 sm:py-16">
      <Link href="/" className="inline-flex items-center gap-1 text-xs text-slate-400 hover:text-slate-700"><ArrowLeft className="w-3.5 h-3.5" /> Back to Home</Link>
      <section className="text-center max-w-3xl mx-auto py-12"><h1 className="public-section-title text-4xl sm:text-5xl">Connect. Donate. Save Lives.</h1><p className="mt-5 public-section-copy text-base">LIFE-LINK is an AI-powered emergency medical resource platform designed to connect voluntary blood donors, emergency hospitals, and regional blood banks through one coordinated network.</p><div className="mt-7 flex justify-center gap-3"><Link href="/choose-role" className="h-11 px-5 rounded-lg bg-blue-600 text-white text-sm font-semibold flex items-center gap-2">Create an account <ArrowRight className="w-4 h-4" /></Link><Link href="/login" className="h-11 px-5 rounded-lg border border-slate-200 bg-white text-slate-700 text-sm font-semibold flex items-center">Log in</Link></div></section>
      <section><div className="text-center mb-8"><h2 className="public-section-title">How LIFE-LINK Works</h2><p className="mt-2 public-section-copy">A centralized coordination network linking donors, hospitals, and blood banks.</p></div><div className="grid md:grid-cols-3 gap-5">{workflows.map(({icon:Icon,title,color,items})=><div className="public-card p-6" key={title}><div className={`h-11 w-11 rounded-lg flex items-center justify-center ${color==='red'?'bg-red-50 text-red-500':color==='blue'?'bg-blue-50 text-blue-600':'bg-amber-50 text-amber-600'}`}><Icon className="w-5 h-5"/></div><h3 className="mt-4 text-base font-bold text-slate-900">{title}</h3><ul className="mt-4 space-y-3">{items.map(item=><li key={item} className="flex gap-2 text-xs leading-5 text-slate-500"><CheckCircle2 className="w-4 h-4 shrink-0 text-green-600 mt-0.5"/>{item}</li>)}</ul></div>)}</div></section>
      <section className="mt-12 rounded-2xl bg-blue-600 p-8 sm:p-10 text-center text-white"><h2 className="text-2xl font-extrabold">Ready to Join the LIFE-LINK Network?</h2><p className="mt-2 text-sm text-blue-100">Choose your role and continue with passwordless verification.</p><Link href="/choose-role" className="mt-6 inline-flex h-11 px-5 rounded-lg bg-white text-blue-600 text-sm font-semibold items-center gap-2">Create an account <ArrowRight className="w-4 h-4"/></Link></section>
    </main>
    <footer className="border-t border-slate-200 bg-white"><div className="lifelink-container py-7 text-xs text-slate-500 flex justify-between"><span>© {new Date().getFullYear()} LIFE-LINK</span><div className="flex gap-5"><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/contact">Contact</Link></div></div></footer>
  </div>;
}
